export const resultSearchShip = {
    flag: '',
    name: '',
    types: '',
    code: '',
    tons: '',
    size: '',
    is_ais: false,
    is_vpass: false,
    is_vhf: false,
    is_ff: false,
    region: '',
    port: '',
    sort: '',
    unit: '',
    id: '',
    info: '',
    cnt: 0,
    data: [],
}
