export const KindsOfShip = [
    { value: '정보없음' },
    { value: '어선' },
    { value: '목선' },
    { value: '유선' },
    { value: '어장관리선' },
    { value: '고무보트' },
    { value: '모터보트(레저용)' }, 
    { value: '모터보트(선내기)' }, 
    { value: '모터보트(선외기)' }, 
    { value: '수상오토바이' },
    { value: '세일링보트' },
    { value: '해경정' },
    { value: '무인경비정' },
]