export const detailCommonShip = {
    id: '',
    main_img: '',
    main_img_id: '',
    name: '',
    code: '',
    types: '',
    is_ais: false,
    is_vpass: false,
    is_vhf: false,
    is_ff: false,
    port: '',
    region: '',
    tons: '',
    size: '',
    register: '',
    regit_date: '',
    is_train: false,
    img_cnt: '',
    lat: '',
    lon: '',
    train_img: '',
}
